name = "library-worker"
main = "src/index.ts"
compatibility_date = "2024-05-01"

[[d1_databases]]
binding = "DB"
database_name = "library-db"
database_id = "d37e997b-bb57-4b9c-bb60-6f4d1eafa880"

[[vectorize]]
binding = "VECTORIZE_INDEX"
index_name = "faces-index"